kind: live
title: Example config

defaults:
  # preset: gpu-small
  preset: cpu-small

volumes:
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /project/data
    local: data
    read_only: True
  code:
    remote: storage:${{ flow.project_id }}/modules
    mount: /project/modules
    local: modules
  config:
    remote: storage:${{ flow.project_id }}/config
    mount: /project/config
    local: config
  notebooks:
    remote: storage:${{ flow.project_id }}/notebooks
    mount: /project/notebooks
    local: notebooks
  results:
    remote: storage:${{ flow.project_id }}/results
    mount: /project/results
    local: results
  project:
    remote: storage:${{ flow.project_id }}
    mount: /project
    read_only: True

images:
  img:
    ref: image:${{ flow.project_id }}:v1.0
    dockerfile: ${{ flow.workspace }}/Dockerfile
    context: ${{ flow.workspace }}

jobs:

  test:
    image: ubuntu
    # ${{ flow.id }} calculation displays a yellow warning for deprecated flow.id attr
    cmd: echo ${{ flow.id }}

  bash:
    image: ubuntu

  py:
    image: python:latest
    python: |
        import sys
        print("Hello!!!")
        sys.exit(1)

  develop:
    image: ${{ images.img.ref }}
    # note, since the base image v1.6 redirects the output via '2>&1 | tee'
    # the image cannot run bash in interactive mode.
    cmd: bash
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: ${{ volumes.code.mount }}
    port_forward:
    - "2211:22"

  train:
    image: ${{ images.img.ref }}
    detach: True
    life_span: 10d
    volumes:
      - ${{ volumes.data.ref_ro }}
      - ${{ upload(volumes.code).ref_rw }}
      - ${{ volumes.config.ref_ro }}
      - ${{ volumes.results.ref_rw }}
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: ${{ volumes.code.mount }}
    bash: |
        cd ${{ volumes.project.mount }}
        python ${{ volumes.code.mount }}/train.py --data ${{ volumes.data.mount }}

  multitrain:
    image: ${{ images.img.ref }}
    detach: True
    life_span: 10d
    volumes:
      - ${{ volumes.data.ref_ro }}
      - ${{ upload(volumes.code).ref_rw }}
      - ${{ volumes.config.ref_ro }}
      - ${{ volumes.results.ref_rw }}
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: ${{ volumes.code.mount }}
    multi: true
    bash: |
        cd ${{ volumes.project.mount }}
        python ${{ volumes.code.mount }}/train.py --data ${{ volumes.data.mount }} ${{ multi.args }}

  jupyter:
    action: ws:.neuro/jupyter
    args:
      volume_data: $[[ volumes.data.ref_ro ]]
      volume_code: ${{ upload(volumes.code).ref_rw }}
      volume_config: ${{ volumes.config.ref_ro }}
      volume_notebooks: ${{ volumes.notebooks.ref_rw }}
      volume_results: ${{ volumes.results.ref_rw }}
      python_path: ${{ volumes.code.mount }}
      image: ${{ images.img.ref }}
      notebook_dir: ${{ volumes.notebooks.mount }}

  tensorboard:
    preset: cpu-small
    http_port: 6006
    browse: True
    detach: True
    volumes:
      - ${{ volumes.results.ref_ro }}
    image: tensorflow/tensorflow:latest
    cmd: tensorboard --host=0.0.0.0 --logdir=${{ volumes.results.mount }}

  filebrowser:
    preset: cpu-small
    http_port: 80
    browse: True
    detach: True
    volumes:
      - ${{ volumes.project.remote }}:/srv:rw
    image: filebrowser/filebrowser:latest
    cmd: --noauth
